-- MySQL Script generated by MySQL Workbench
-- Thu Dec 20 10:13:32 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema db_action_tracker
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema db_action_tracker
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `db_action_tracker` DEFAULT CHARACTER SET utf8 ;
USE `db_action_tracker` ;

-- -----------------------------------------------------
-- Table `db_action_tracker`.`user`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `db_action_tracker`.`user` ;

CREATE TABLE IF NOT EXISTS `db_action_tracker`.`user` (
  `User_email` VARCHAR(150) NOT NULL,
  `User_service` LONGTEXT NULL,
  `User_department` LONGTEXT NULL,
  `User_direction` LONGTEXT NULL,
  `User_n1email` VARCHAR(150) NULL,
  `User_n2email` VARCHAR(150) NULL,
  `User_n3email` VARCHAR(150) NULL,
  PRIMARY KEY (`User_email`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_action_tracker`.`Task`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `db_action_tracker`.`Task` ;

CREATE TABLE IF NOT EXISTS `db_action_tracker`.`Task` (
  `Task_id` INT NOT NULL AUTO_INCREMENT,
  `Task_title` VARCHAR(150) NULL,
  `Task_description` LONGTEXT NULL,
  `Task_date_start_wished` DATETIME NULL,
  `Task_date_end` DATETIME NULL,
  `Task_priority_level` INT NULL,
  `Task_status` VARCHAR(45) NULL,
  `Task_dependency_id` INT NULL,
  `Task_user_initiator_email` VARCHAR(255) NOT NULL,
  `Task_user_collaborator_email` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`Task_id`),
  INDEX `fk_Action_Initiateur1_idx` (`Task_user_initiator_email` ASC),
  CONSTRAINT `fk_Action_Initiateur1`
    FOREIGN KEY (`Task_user_initiator_email`)
    REFERENCES `db_action_tracker`.`user` (`User_email`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_action_tracker`.`Comments`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `db_action_tracker`.`Comments` ;

CREATE TABLE IF NOT EXISTS `db_action_tracker`.`Comments` (
  `Comment_id` INT NOT NULL AUTO_INCREMENT,
  `Comment_content` LONGTEXT NULL,
  `Comment_date` DATETIME NULL,
  `Comment_task_id` INT NOT NULL,
  `Comment_user_initiator_email` VARCHAR(255) NOT NULL,
  `Comment_user_collaborator_email` VARCHAR(255) NULL,
  PRIMARY KEY (`Comment_id`),
  INDEX `fk_Commentaires_Action1_idx` (`Comment_task_id` ASC),
  INDEX `fk_Commentaires_Initiateur1_idx` (`Comment_user_initiator_email` ASC),
  CONSTRAINT `fk_comment_Action1`
    FOREIGN KEY (`Comment_task_id`)
    REFERENCES `db_action_tracker`.`Task` (`Task_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_comment_Initiateur1`
    FOREIGN KEY (`Comment_user_initiator_email`)
    REFERENCES `db_action_tracker`.`user` (`User_email`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_action_tracker`.`Project`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `db_action_tracker`.`Project` ;

CREATE TABLE IF NOT EXISTS `db_action_tracker`.`Project` (
  `Project_id` INT NOT NULL AUTO_INCREMENT,
  `Project_name` VARCHAR(100) NOT NULL,
  `Project_description` LONGTEXT NULL,
  `Project_start_date` DATE NULL,
  `Project_end_date` DATE NULL,
  `Project_status` VARCHAR(150) NULL,
  `Project_user_initiator_email` VARCHAR(255) NOT NULL,
  `Project_tasks_id_list` VARCHAR(255) NULL,
  PRIMARY KEY (`Project_id`),
  INDEX `fk_Projet_Initiateur1_idx` (`Project_user_initiator_email` ASC),
  CONSTRAINT `fk_Projet_Initiateur1`
    FOREIGN KEY (`Project_user_initiator_email`)
    REFERENCES `db_action_tracker`.`user` (`User_email`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_action_tracker`.`Problem`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `db_action_tracker`.`Problem` ;

CREATE TABLE IF NOT EXISTS `db_action_tracker`.`Problem` (
  `Problem_id` INT NOT NULL AUTO_INCREMENT,
  `Problem_starting_date` DATE NULL,
  `Problem_resolved_date` DATE NULL,
  `Problem_description` LONGTEXT NULL,
  `Problem_status` VARCHAR(45) NOT NULL,
  `Problem_cause` LONGTEXT NULL,
  `Problem_rootcause` LONGTEXT NULL,
  `Problem_ocean_ticket` VARCHAR(255) NULL,
  `problem_pilote_initiateur_email` VARCHAR(255) NOT NULL,
  `problem_tasks_id_list` VARCHAR(255) NULL,
  PRIMARY KEY (`Problem_id`),
  INDEX `fk_Problem_Initiateur1_idx` (`problem_pilote_initiateur_email` ASC),
  CONSTRAINT `fk_Problem_Initiateur1`
    FOREIGN KEY (`problem_pilote_initiateur_email`)
    REFERENCES `db_action_tracker`.`user` (`User_email`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
